[theme]
# Cor dos botões, seletores ativos e destaques principais (Azul Corporativo)
primaryColor = "#0080FF"

# Cor de fundo principal da página (Escuro Slate 900)
backgroundColor = "#0F172A"

# Cor de fundo da barra lateral e dos blocos/cartões (Slate 800)
secondaryBackgroundColor = "#1E293B"

# Cor dos textos gerais (Off-white)
textColor = "#F8FAFC"

# Estilo da fonte
font = "sans serif"
